travis:
  secure:
    BINSTAR_TOKEN: JZJkbtdf/F0piYhqXQvp6BUYRNVm9aqi1JamE6LB9/x0jlMt2jAeFS8x/i9kn4DYJxBrslGJGInFi5iUyuvn1eXxRvB+j0UV1Kkx/vHVpvSjg3TuoMM743nNoTqAmbccHicew+KIbUUjEwJZvjlKanu0TADcWfz33/e4q27towTo9D+PIbiCWkivDlvOOxFdfOIhYmxQ4hv+QizJbFv/mmUrr+WiJX1n2NwD0kKj7Zg7na/vaxzU1/+Z42ne/sB8JIBkIeJz1q+iakZVigVS2qC5kpZib8FP8bkOmGxo5lkToa17jZtcoKP+nnWYcximS4kTIK49ttjx1+ZiSkH2juqa7E8skofQXCky2KxQwX3l6+BnJUd7uzkTdTEKqkFVOL2MOb4wDNXDhph2HlE/aOknxLioDoUCsvas9w1cVEcsvf26N9w6QdG8KnHkX3Fxo464NW6P563lGGcO1ZeYXZ2imwYZ4++ztwxTocTLMUTkTD1VtYjWq6/rG/W0xYEan9PCZ/NsiiAV0dirJQlT/yU7nEN2fjfKxsXUZosxvDdP2YQAZ+hIRGED3b/TdynIgKOcggYdFPPfdOs4cIldK7NVUMZDmXX3njDUQgBdY/uesEAiV1ssc9g6HWqlSO6QGAxvd4Rb69doLu2gDnxPpiqHREebLNlEoVtm/SyDwvY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
